jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: >-
          curl -X GET  -H "Content-type: application/xml" -H "Accept:
          application/xml" 
          "http://admin:admin@localhost:8111/app/rest/projects"
    parameters:
      env.s: s
  Job2:
    name: Job 2
    steps:
      - type: script
        script-content: >-
          curl -X GET  -H "Content-type: application/xml" -H "Accept: application/xml"  "http://localhost:8111/app/rest/projects/id:Word1word2word3word4word5word6word7word8word9word10word11word12word1"
